from ast_nodes import (
    LoadNode, FilterNode, GroupByNode, AggregateNode,
    SortNode, DisplayNode, ExportNode, ChartNode, PipelineNode,
)


class CodeGenError(Exception):
    pass


class CodeGenerator:
    """
    Walks a BizLang PipelineNode and emits a complete, executable Python script
    that uses pandas and matplotlib — no BizLang runtime required.
    """

    def __init__(self):
        self._has_group_by  = False
        self._group_column  = None

    def generate(self, pipeline: PipelineNode) -> str:
        self._validate(pipeline)

        lines: list[str] = [
            "# Generated by BizLang — bizlang.io",
            "# Run this file directly with: python output.py",
            "",
            "import pandas as pd",
            "import matplotlib.pyplot as plt",
            "",
        ]

        for step in pipeline.steps:
            if isinstance(step, LoadNode):
                lines.extend(self._visit_load(step))
            elif isinstance(step, FilterNode):
                lines.extend(self._visit_filter(step))
            elif isinstance(step, GroupByNode):
                lines.extend(self._visit_group_by(step))
            elif isinstance(step, AggregateNode):
                lines.extend(self._visit_aggregate(step))
            elif isinstance(step, SortNode):
                lines.extend(self._visit_sort(step))
            elif isinstance(step, DisplayNode):
                lines.extend(self._visit_display(step))
            elif isinstance(step, ExportNode):
                lines.extend(self._visit_export(step))
            elif isinstance(step, ChartNode):
                lines.extend(self._visit_chart(step))
            else:
                raise CodeGenError(f"Unknown node type: {type(step).__name__}")

        return "\n".join(lines)

    # ── Validation ────────────────────────────────────────────────────────────

    def _validate(self, pipeline: PipelineNode) -> None:
        steps = pipeline.steps
        if not steps:
            raise CodeGenError("Pipeline has no steps.")
        if not isinstance(steps[0], LoadNode):
            raise CodeGenError("First command must be 'load'.")
        for step in steps[:-1]:
            if isinstance(step, ChartNode):
                raise CodeGenError("'chart' must be the last command.")
        seen_agg = False
        for step in steps:
            if isinstance(step, AggregateNode):
                seen_agg = True
            if isinstance(step, GroupByNode) and seen_agg:
                raise CodeGenError("'group by' must come before aggregation.")

    # ── Visitors ──────────────────────────────────────────────────────────────

    def _visit_load(self, node: LoadNode) -> list[str]:
        return [
            "# ── load ──────────────────────────────────────────────────────",
            f'df = pd.read_csv("{node.filename}")',
            'print(f"Loaded {len(df):,} rows · {len(df.columns)} columns")',
            'print(df)',
            'print()',
            '',
        ]

    def _visit_filter(self, node: FilterNode) -> list[str]:
        py_op_map = {"=": "==", "!=": "!=", ">": ">", "<": "<", ">=": ">=", "<=": "<="}
        parts = []
        for cond in node.conditions:
            py_op = py_op_map[cond.operator]
            try:
                float(cond.value)
                py_val = cond.value
            except ValueError:
                py_val = f'"{cond.value}"'
            parts.append(f'(df["{cond.column}"] {py_op} {py_val})')

        connector = " & " if node.logic == "AND" else " | "
        mask_expr = connector.join(parts)
        desc = f" {node.logic} ".join(
            f"{c.column} {c.operator} {c.value}" for c in node.conditions
        )
        return [
            f"# ── filter: {desc} ──",
            f"df = df[{mask_expr}]",
            f'print(f"After filter — {{len(df):,}} rows remain")',
            'print(df)',
            'print()',
            '',
        ]

    def _visit_group_by(self, node: GroupByNode) -> list[str]:
        self._has_group_by = True
        self._group_column = node.column
        return [
            f"# ── group by {node.column} ── (applied with next aggregation)",
            f'_group_col = "{node.column}"',
            '',
        ]

    def _visit_aggregate(self, node: AggregateNode) -> list[str]:
        func_map   = {"sum": "sum", "avg": "mean", "count": "count"}
        pandas_fn  = func_map[node.function]

        if self._has_group_by:
            return [
                f"# ── {node.function}({node.column}) grouped by {self._group_column} ──",
                f'df = df.groupby(_group_col)["{node.column}"].agg("{pandas_fn}").reset_index()',
                f'print(f"After {node.function} — {{len(df)}} groups")',
                'print(df)',
                'print()',
                '',
            ]
        else:
            label = f"{node.function}({node.column})"
            return [
                f"# ── {label} (scalar) ──",
                f'_result = df["{node.column}"].agg("{pandas_fn}")',
                f'print(f"{label} = {{_result:,.4g}}")',
                '',
            ]

    def _visit_sort(self, node: SortNode) -> list[str]:
        ascending = "True" if node.order == "asc" else "False"
        return [
            f"# ── sort {node.column} {node.order} ──",
            f'df = df.sort_values("{node.column}", ascending={ascending}).reset_index(drop=True)',
            f'print(f"Sorted by {node.column} ({node.order})")',
            'print(df)',
            'print()',
            '',
        ]

    def _visit_display(self, node: DisplayNode) -> list[str]:
        if node.limit:
            return [
                f"# ── display top {node.limit} ──",
                f'print("Dataset (top {node.limit} rows):")',
                f'print(df.head({node.limit}))',
                'print()',
                '',
            ]
        return [
            "# ── display ──",
            'print("Dataset:")',
            'print(df)',
            'print()',
            '',
        ]

    def _visit_export(self, node: ExportNode) -> list[str]:
        if node.fmt == "json":
            write_call = f'df.to_json("{node.filename}", orient="records", indent=2)'
        else:
            write_call = f'df.to_csv("{node.filename}", index=False)'
        return [
            f"# ── export → {node.filename} ──",
            write_call,
            f'print(f"Exported {{len(df):,}} rows to {node.filename}")',
            '',
        ]

    def _visit_chart(self, node: ChartNode) -> list[str]:
        x, y   = node.x_column, node.y_column
        ctype  = node.chart_type
        xtitle = x.replace("_", " ").title()
        ytitle = y.replace("_", " ").title()

        lines = [
            f"# ── chart {ctype} {x} {y} ──",
            'plt.figure(figsize=(10, 5))',
        ]

        if ctype == "bar":
            lines += [
                f'plt.bar(df["{x}"], df["{y}"], color="#4A90D9", edgecolor="white")',
                f'plt.xlabel("{xtitle}", fontsize=11)',
                f'plt.ylabel("{ytitle}", fontsize=11)',
                f'plt.title("{ytitle} by {xtitle}", fontsize=14, fontweight="bold")',
                'plt.gca().spines[["top","right"]].set_visible(False)',
            ]
        elif ctype == "line":
            lines += [
                f'plt.plot(df["{x}"], df["{y}"], marker="o", color="#4A90D9", linewidth=2)',
                f'plt.xlabel("{xtitle}", fontsize=11)',
                f'plt.ylabel("{ytitle}", fontsize=11)',
                f'plt.title("{ytitle} over {xtitle}", fontsize=14, fontweight="bold")',
                'plt.gca().spines[["top","right"]].set_visible(False)',
            ]
        elif ctype == "pie":
            lines += [
                f'plt.pie(df["{y}"], labels=df["{x}"], autopct="%1.1f%%", startangle=140)',
                f'plt.title("{ytitle} by {xtitle}", fontsize=14, fontweight="bold")',
            ]

        lines += [
            'plt.tight_layout()',
            'plt.savefig("chart_output.png", dpi=150, bbox_inches="tight")',
            'print("Chart saved → chart_output.png")',
            'plt.show()',
            '',
        ]
        return lines
