# codegen.py
# ─────────────────────────────────────────────────────────────────────────────
# BizLang Code Generator
#
# Walks a PipelineNode AST top-to-bottom and emits a complete, executable
# Python script that uses pandas and matplotlib.
#
# Design:
#   - One method per node type (visit_* pattern, but hand-rolled and simple)
#   - All generated code goes into a list of strings (lines)
#   - At the end, lines are joined with newlines into one script string
# ─────────────────────────────────────────────────────────────────────────────

from ast_nodes import (
    LoadNode, FilterNode, GroupByNode,
    AggregateNode, ChartNode, PipelineNode,
)


class CodeGenError(Exception):
    """Raised when the AST has an illegal or unsupported combination of nodes."""
    pass


class CodeGenerator:
    """
    Converts a BizLang PipelineNode AST into executable Python source code.

    Usage:
        gen  = CodeGenerator()
        code = gen.generate(pipeline_node)
        print(code)
    """

    def __init__(self):
        # We keep track of which nodes we've seen to validate combinations
        self._has_load      = False
        self._has_group_by  = False
        self._has_aggregate = False
        self._group_column  = None   # needed for chart axis logic

    # ── Public entry point ────────────────────────────────────────────────────

    def generate(self, pipeline: PipelineNode) -> str:
        """
        Walk the PipelineNode and return a complete Python script as a string.
        """
        print("── Generating Python Code ─────────────────────────────────────")

        self._validate_pipeline(pipeline)

        lines = []

        # ── Imports ───────────────────────────────────────────────────────────
        lines.append("# Generated by BizLang Code Generator")
        lines.append("# Run this file directly with: python output.py")
        lines.append("")
        lines.append("import pandas as pd")
        lines.append("import matplotlib.pyplot as plt")
        lines.append("")

        # ── Walk each step ────────────────────────────────────────────────────
        for step in pipeline.steps:
            node_type = type(step).__name__
            print(f"  Generating code for {node_type}")

            if isinstance(step, LoadNode):
                lines.extend(self._visit_load(step))
            elif isinstance(step, FilterNode):
                lines.extend(self._visit_filter(step))
            elif isinstance(step, GroupByNode):
                lines.extend(self._visit_group_by(step))
            elif isinstance(step, AggregateNode):
                lines.extend(self._visit_aggregate(step))
            elif isinstance(step, ChartNode):
                lines.extend(self._visit_chart(step))
            else:
                raise CodeGenError(f"Unknown node type: {node_type}")

        print()
        return "\n".join(lines)

    # ── Validation ────────────────────────────────────────────────────────────

    def _validate_pipeline(self, pipeline: PipelineNode) -> None:
        """
        Check that the pipeline makes semantic sense before generating code.
        Rules:
          - First step must be 'load'
          - 'group by' must come before any aggregation
          - 'chart' must be the last step
        """
        steps = pipeline.steps
        if not steps:
            raise CodeGenError("Pipeline has no steps.")

        if not isinstance(steps[0], LoadNode):
            raise CodeGenError(
                "The first command in a pipeline must be 'load'.\n"
                f"  Got: {type(steps[0]).__name__}"
            )

        if isinstance(steps[-1], ChartNode) is False and \
           any(isinstance(s, ChartNode) for s in steps):
            raise CodeGenError("'chart' must be the last command in the pipeline.")

        # Check group by comes before aggregate
        seen_aggregate = False
        for step in steps:
            if isinstance(step, AggregateNode):
                seen_aggregate = True
            if isinstance(step, GroupByNode) and seen_aggregate:
                raise CodeGenError(
                    "'group by' must come before 'sum', 'avg', or 'count'."
                )

    # ── Node visitors ─────────────────────────────────────────────────────────

    def _visit_load(self, node: LoadNode) -> list[str]:
        """
        Generates:
            df = pd.read_csv("sales.csv")
            print(df)
        """
        self._has_load = True
        return [
            f'# Step: load',
            f'df = pd.read_csv("{node.filename}")',
            f'print("Loaded data:")',
            f'print(df)',
            f'print()',
            f'',
        ]

    def _visit_filter(self, node: FilterNode) -> list[str]:
        """
        Generates a pandas boolean mask filter.
        Handles numeric vs string values automatically.

        Examples:
            df = df[df["region"] == "South"]
            df = df[df["revenue"] > 100]
        """
        col = node.column
        op  = node.operator
        val = node.value

        # Map BizLang operators to Python operators
        op_map = {
            "=":  "==",
            "!=": "!=",
            ">":  ">",
            "<":  "<",
            ">=": ">=",
            "<=": "<=",
        }
        py_op = op_map.get(op, "==")

        # Decide whether to quote the value (strings) or not (numbers)
        try:
            float(val)          # if this succeeds, it's numeric
            py_val = val
        except ValueError:
            py_val = f'"{val}"' # it's a string — wrap in quotes

        return [
            f'# Step: filter {col} {op} {val}',
            f'df = df[df["{col}"] {py_op} {py_val}]',
            f'print("After filter ({col} {op} {val}):")',
            f'print(df)',
            f'print()',
            f'',
        ]

    def _visit_group_by(self, node: GroupByNode) -> list[str]:
        """
        Does NOT emit code yet — we store the group column and emit
        the full groupby().agg() call when we see the AggregateNode.
        This mirrors how pandas groupby + agg work together.
        """
        self._has_group_by = True
        self._group_column = node.column

        return [
            f'# Step: group by {node.column}',
            f'# (aggregation will be applied in the next step)',
            f'_group_col = "{node.column}"',
            f'',
        ]

    def _visit_aggregate(self, node: AggregateNode) -> list[str]:
        """
        Generates the groupby + aggregation.

        If group by was seen:
            df = df.groupby("month")["revenue"].sum().reset_index()
        If no group by:
            result = df["revenue"].sum()
            print(result)
        """
        self._has_aggregate = True
        func   = node.function
        col    = node.column

        # Map BizLang function names to pandas method names
        pandas_func_map = {
            "sum":   "sum",
            "avg":   "mean",
            "count": "count",
        }
        pandas_func = pandas_func_map[func]

        if self._has_group_by:
            return [
                f'# Step: {func} {col} (with group by {self._group_column})',
                f'df = df.groupby(_group_col)["{col}"].{pandas_func}().reset_index()',
                f'print("After group by + {func}:")',
                f'print(df)',
                f'print()',
                f'',
            ]
        else:
            # No group by — just compute a scalar
            return [
                f'# Step: {func} {col} (no group by)',
                f'_result = df["{col}"].{pandas_func}()',
                f'print(f"{func.upper()} of {col}: {{_result}}")',
                f'',
            ]

    def _visit_chart(self, node: ChartNode) -> list[str]:
        """
        Generates matplotlib chart code.

        Supported types:
          - bar:  plt.bar(x, y)
          - line: plt.plot(x, y)
          - pie:  plt.pie(y, labels=x)
        """
        x   = node.x_column
        y   = node.y_column
        ctype = node.chart_type

        lines = [
            f'# Step: chart {ctype} {x} {y}',
            f'plt.figure(figsize=(8, 5))',
        ]

        if ctype == "bar":
            lines += [
                f'plt.bar(df["{x}"], df["{y}"], color="steelblue", edgecolor="white")',
                f'plt.xlabel("{x.capitalize()}")',
                f'plt.ylabel("{y.capitalize()}")',
                f'plt.title("{y.capitalize()} by {x.capitalize()}")',
            ]
        elif ctype == "line":
            lines += [
                f'plt.plot(df["{x}"], df["{y}"], marker="o", color="steelblue", linewidth=2)',
                f'plt.xlabel("{x.capitalize()}")',
                f'plt.ylabel("{y.capitalize()}")',
                f'plt.title("{y.capitalize()} over {x.capitalize()}")',
            ]
        elif ctype == "pie":
            lines += [
                f'plt.pie(df["{y}"], labels=df["{x}"], autopct="%1.1f%%")',
                f'plt.title("{y.capitalize()} by {x.capitalize()}")',
            ]

        lines += [
            f'plt.tight_layout()',
            f'plt.savefig("chart_output.png")',
            f'print("Chart saved to chart_output.png")',
            f'plt.show()',
            f'',
        ]
        return lines
