# Generated by BizLang Code Generator
# Run this file directly with: python output.py

import pandas as pd
import matplotlib.pyplot as plt

# Step: load
df = pd.read_csv("sample_data/sales.csv")
print("Loaded data:")
print(df)
print()

# Step: filter region = South
df = df[df["region"] == "South"]
print("After filter (region = South):")
print(df)
print()

# Step: group by month
# (aggregation will be applied in the next step)
_group_col = "month"

# Step: sum revenue (with group by month)
df = df.groupby(_group_col)["revenue"].sum().reset_index()
print("After group by + sum:")
print(df)
print()

# Step: chart bar month revenue
plt.figure(figsize=(8, 5))
plt.bar(df["month"], df["revenue"], color="steelblue", edgecolor="white")
plt.xlabel("Month")
plt.ylabel("Revenue")
plt.title("Revenue by Month")
plt.tight_layout()
plt.savefig("chart_output.png")
print("Chart saved to chart_output.png")
plt.show()
